version: "3.1"

services:
  postgresql:
    image: postgres
    ports:
      - "5433:5432"
    env_file:
      - ./.env
    volumes:
      - meu_volume_postgres:/var/lib/postgresql/data

volumes:
  meu_volume_postgres:
